# Generated by Django 5.0.2 on 2024-03-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_screener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
