# Generated by Django 5.0.3 on 2024-03-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_screener', '0003_alter_applicants_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=255)),
                ('job_Category', models.CharField(max_length=255)),
                ('keywords', models.TextField()),
                ('job_description', models.TextField()),
                ('skills', models.TextField()),
                ('education', models.TextField()),
            ],
        ),
    ]
