# Generated by Django 5.0.3 on 2024-03-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_screener', '0004_jobopening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='last_name',
        ),
    ]
