# Generated by Django 5.0.3 on 2024-03-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_screener', '0006_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='certifications',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobopening',
            name='experience',
            field=models.TextField(default='Temp'),
            preserve_default=False,
        ),
    ]
